config/routes.rb
Rails.application.routes.draw do
  root 'tracks#home'

  get 'videos/new'
  get 'videos/edit'
  get 'videos/index'
  get 'videos/show'
  get 'tracks/new'
  get 'tracks/create'
  get 'tracks/edit'
  get 'tracks/update'
  get 'tracks/show'
  get 'tracks/index'
  get 'tracks/destroy'
  get 'tracks/search', to: 'tracks#search'
  get 'password_resets/new'
  get 'password_resets/edit'
	# For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
    
  get '/signup', to: 'users#new'
  get '/in-kuerze', to:  'static_pages#in_kuerze' #test 
  get '/ueber-mich', to: 'static_pages#ueber_mich'
  get '/impressum', to: 'static_pages#impressum'
  get '/datenschutz', to: 'static_pages#datenschutz'
  get '/kontakt', to: 'static_pages#kontakt'
  get '/all_tracks', to: 'tracks#all_tracks'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  

  resources :users
  resources :videos
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]

  get '/music', to: 'tracks#music'

  resources :tracks



end

app/models/track.rb
class Track < ApplicationRecord
	belongs_to :user
	belongs_to :category
	has_one_attached :image
	has_one_attached :audio
	default_scope -> {order(created_at: :desc)}
	validates :title, presence: true, uniqueness: true
	validates :item_number, presence: true, uniqueness: true
	validates :user_id, presence: true
	validates :image, presence: true, content_type: { in: %w[image/jpeg image/jpg image/png image/gif], message: "must be a valid image format: JPEG, PNG or GIF" },
										size: 				{ less_than: 5.megabytes, message: "is too big. It should be less than 5 MB" }
	validates :audio, presence: true, content_type: { in: %w[audio/x-wav audio/mpeg], message: "must be a valid format: WAV or MP3"}

	has_many :track_videos
	has_many :videos, through: :track_videos
	self.per_page = 15

	# Returns a resized image for display
	def display_image
		image.variant(resize_to_limit: [650, 650])
	end
end

app/controllers/tracks_controller.rb
class TracksController < ApplicationController
  before_action :logged_in_user, only: [:new, :create, :edit, :update, :index, :destroy]  # logged_in_user method defined in app/helpers/sessions_helpers.rb
  before_action :get_user, only: [:new, :create, :edit, :update, :index, :destroy] # get_user method defined in /app/heplers/sessions_helper.rb
  before_action :about_track, only: [:edit, :update, :show, :destroy]
  before_action :force_json, only: :search

  # Randomly chooses 4 tracks to display on the homepage
  def home
    @chosen_tracks = Track.all.sample(4)
  end

  def new
    @track = @user.tracks.build
  end

  # Creates a new track
  def create
    @track = @user.tracks.build(track_params)
    @track.image.attach(params[:track][:image])
    @track.audio.attach(params[:track][:audio])
    if @track.save
      if @track.published_status
        @track.update_attribute(:published_at, Time.zone.now)
      end
      flash[:success] = "Neuer Track wurde erstellt" # success message: New track has been created
      redirect_to @track
    else
      render 'new'
    end
  end

  def edit
  end

  # Updates a track
  def update
    if @track.update(track_params)
      flash[:success] = "Deine Änderungen wurden gespeichert." # success messages: Your changes have been saved.
      redirect_to @track
    else
      flash.now[:danger] = "Deine Änderungen wurden nicht gespeichert." # failure message: Your changes have not been saved.
      render 'edit'
    end
  end

  # Shows a track
  def show
    @cat_parent = Category.find_by(id: @track.category_id).parent
    @cat = Category.find_by(id: @track.category_id)
  end

  # Shows all tracks, according to the chosen filter option
  def index
    if Track.all.size == 0
      flash[:danger] = "No tracks exist yet."
      redirect_to new_track_path
    end

    # Shows all published tracks    
    if (params[:published] == '1') && (params[:unpublished] == '0') 
      @tracks = Track.where(published_status: true)

    # Shows all unpublished tracks
    elsif (params[:published] == '0') && (params[:unpublished] == '1')
      @tracks = Track.where(published_status: false)

      # For non-admins show only their own unpublished tracks
      if !super_admin_user?(@user)
        @tracks = @tracks.where("user_id=?", @user.id)
      end

    # For non-admins show all published and all own unpublished tracks
    # For admins show all tracks
    else
      if !super_admin_user?(@user)
        @tracks = Track.where(published_status: true).or(Track.where("user_id=?", @user.id))
      else
        @tracks = Track.all
      end
    end

    # Adds pagination
    @tracks = @tracks.paginate(page: params[:page])
  end


  # Destroys a track
  def destroy
    title = @track.title    
    if @track.destroy
      flash[:success] = "Track '#{title}' gelöscht." # success message: Track destroyed.
      redirect_to tracks_path
    end  
  end

  # Shows all published tracks according to the chosen category
  def music

    # Show all published tracks
    if params[:category_id].blank? 
      @tracks = Track.where(published_status: true)
    else
      @category = Category.find_by(id: params[:category_id])

      # Show tracks in the chosen subcategory
      if @category.has_parent? 
        @tracks = Track.where(published_status: true, category_id: params[:category_id])

      # Show tracks in the chosen main category  
      else 
        @tracks = Track.where(published_status: true, category_id: @category.child_ids)
      end
    end

  end

  def search
    t = params[:t].downcase
    @tracks = Track.where("title LIKE ?", "%#{t}%")
  end

  private

    # Declares which track attributes may be modified through the web
    def track_params
      params.require(:track).permit(:title, :description, :item_number, :composer, :category_id, :published_status, :image, :audio)
    end


    # Gets information about a track
    def about_track
      @track = Track.find_by(id: params[:id])

      if !@track
        flash[:danger] = "Der gesuchte Track existiert nicht." # failure message: The requested track does not exist.
        redirect_to root_url
      end

      # Prepares flash messages for different actions
      if "edit_update_destroy".include?(params[:action])
        
        if params[:action] == 'edit'
          action = "Bearbeitung von #{@track.title}" # action = "Editing of ..."
        elsif params[:action] == 'update'
          action = "Speicherung der Änderungen für #{@track.title}" # action = "Saving of changes for ..."
        elsif params[:action] == 'destroy'
          action = "Löschung des Tracks" # action = "Deleting of track"
        end

        # If the logged in user is neither the author of the track nor admin/superadmin
        if ((@track.user_id != @user.id) && !super_admin_user?(@user)) 
          flash[:danger] = "Du hast keine Berechtigung für #{action}" # failure message: You don't have the persmission for ...
          redirect_to root_url
        end
        
      end

    end

    def force_json
      request.format = :json
    end
end

app/helpers/tracks_helper.rb
module TracksHelper

	# Renders published status information about a track - for certain development puposes only
	def index_tracks(track)
		render html: "<p style= 'color: red;'>Hier kommt der Status: #{track.published_status}</p>"
	end

end

app/views/tracks/_track.html.erb
<!-- use only for certain actions in tracks controller; use not on users profile page -->
<% if (params[:controller] == "tracks") && (params[:action] == "music" || params[:action] == "home") || 
																					 (params[:action] == 'show' && !request.path.include?('/users')) %>
	<div class="all-tracks-row-item">
		<%= image_tag track.display_image, alt: "#{track.image.filename}" %>
		
		<div class="all-tracks-row-info">
			<div class="all-tracks-row-title">
				<h3><%= link_to track.title, track %></h3>
			</div>
			<div class="all-tracks-row-audio">
				<%= audio_tag(url_for(track.audio), controls: '') %>
			</div>
		</div>
	</div>

<!-- use for index view and on users profile page -->
<% else %>
	<div class="index-row-wrapper">
		<div class="index-row index-row-title"><%= link_to track.title, track %></div>
		<% if track.published_status %>
			<div class="index-row">Online</div>
		<% else %>
			<div class="index-row">Entwurf</div>
		<% end %>
		<% user = User.find_by(id: track.user_id) %>
		<% if !(params[:controller] == "users" && params[:action] == "show") %>
		<div class="index-row">
			<% if request.get? && request.path.include?(tracks_path) %>
				<%= link_to user.name, user %>
			<% elsif request.get? && request.path == "/users/#{params[:id]}" %>
				<%= user.name %>
			<% end %>
		</div>
		<% end %>
		<div class="index-row index-aktionen">
			<% if current_user && ((track.user_id == current_user.id) || super_admin_user?(current_user)) %>
				<span><%= link_to "Bearbeiten", edit_track_path(track), class: 'user-edit-button'%></span>
				<span><%= link_to "Löschen", track_path(track), method: :delete, 
									data: {confirm: "Willst Du wirklich diesen Track löschen?"}, 
									class: 'user-edit-button', id: 'track-delete-button' %></span>
			<% else %>
				<span>--</span>
			<% end %>
		</div>
	</div>	
<% end %>

app/views/tracks/all_tracks.html.erb
<% provide(:title, 'Alle Tracks') %>

<div class="single-page" id="all-tracks-page">
	
	<% if params[:category_id].blank? %>
		<h2>Alle Tracks (<%= @tracks.size %>)</h2>
	<% else %>
		<% if @category.parent %>
			<h2>Kategorie <%= @category.parent.title %> - <%= @category.title %> (<%= @tracks.size %>)</h2>
		<% else %>
			<h2>Kategorie <%= @category.title %> (<%= @tracks.size %>) </h2>
		<% end %>
	<% end %>

	<div id="category-filter">
		<%= form_with(url: all_tracks_url, method: :get, local: true) do |f| %>


  	<%= f.select(:category_id, nested_dropdown(Category.all.arrange), prompt: "Kategorie wählen",) %>

		<%= f.submit "Filtern", class:'user-edit-button' %>
		<%= f.submit "Zurücksetzen", class:'user-edit-button' %>

		<% end %>
	</div>

	<div class="all-tracks-table">
		<%= render @tracks %>		
	</div>
</div>

app/views/tracks/create.html.erb
<h1>Tracks#create</h1>
<p>Find me in app/views/tracks/create.html.erb</p>

app/views/tracks/edit.html.erb
<% provide(:title, @track.title )%>
<% provide(:button_text, "Speichern") %>

<div class="single-page" id="edit-track-page">

	<h2>Bearbeiten von <%= @track.title %></h2>
	<%= render 'shared/track_form' %>
	
</div>

app/views/tracks/home.html.erb
<div class="single-page" id="homepage">
	<h2>Gemafreie Musik ohne Einschränkungen für maximale Freiheit im Projekt</h2>
	<p>
		Gemafreie Musik muss nicht schlecht sein. Mit dieser noch kleinen Musikplattform biete ich dir Musik für deine Projekte - vom privaten You-Tube-Video bis zum TV-Werbespot. Die Musik steht im Rahmen der <%= link_to "CC BY", "https://creativecommons.org/licenses/?lang=en" %>-Lizenz kostenlos zum Download bereit. <br>
		Um die Musik downzuloaden, einfach auf den Titel eines Stückes klicken und im neu geöffneten Bereich downloaden.<br>
		Mehr Infos: <%= link_to "In Kürze", in_kuerze_path %>.
	</p>
	<p>
		Viel Spaß beim Durchstöbern, <br>
		<i>Konrad</i>
	</p>

	<h2>Kleine Auswahl</h2>
	<div class="all-tracks-table">
		<%= render @chosen_tracks %>
	</div>
	<div id="more-tracks-button">
		<%= link_to "Weitere Tracks ansehen", music_path, class:'user-edit-button' %>
	</div>
</div>

app/views/tracks/index.html.erb
<% provide(:title, "Alle Tracks") %>

<div class="single-page" id="alle-tracks-page">

	<h2>Alle Tracks <%= link_to (fa_icon "plus-circle"), new_track_path, class: "h2-fa-icon", id: "h2-fa-icon-create-track", alt: "Neuen Track erstellen", title: "Neuen Track erstellen" %> </h2>

	<div id="track-filter">
		<span>Track-Status: </span>
		<%= form_with(url: tracks_url, method: :get, local: true) do |f| %>
				<%= f.label :published do %>
					<%= f.check_box :published %>
					<span>Online</span>
				<% end %>

				<%= f.label :unpublished do %>
					<%= f.check_box :unpublished %>
					<span>Entwurf</span>
				<% end %>

			<%= f.submit "Filtern" %>

		<% end %>
	</div>

	<div>
		<p>Anzahl der Tracks: <%= @tracks.count %> </p>
	</div>
	<div class="index-table">
		<div class="index-heading">Titel</div>
		<div class="index-heading">Status</div>
		<div class="index-heading">Erstellt von</div>
		<div class="index-heading index-aktionen" id="index-heading-aktionen">Aktionen</div>
		
		<!-- show all tracks in all other cases -->
		<%= render @tracks %>
		<%= will_paginate %>
	</div>

</div>

app/views/tracks/index_archive.html.erb
		
		<% @tracks.each do |t| %>
			<div class="index-row-wrapper">

				<% if (params[:published] == '1') || ((params[:published] == '0') && (params[:unpublished] == '0')) || (!params[:published] && !params[:unpublished]) %>
					<% if t.published_status %>
						<div class="index-row index-row-title"><%= link_to t.title, t %></div>
						<div class="index-row">Online</div>
						<div class="index-row index-aktionen">
							<span><%= link_to "Bearbeiten", edit_track_path(t), class: 'user-edit-button'%></span>
							<span><%= link_to "Löschen", track_path(t), method: :delete, data: {confirm: "Willst Du wirklich diesen Track löschen?"}, class: 'user-edit-button', id: 'track-delete-button' %></span>
						</div>
					<% end %>
				<% end %>

				<% if (params[:unpublished] == '1') || ((params[:published] == '0') && (params[:unpublished] == '0')) || (!params[:published] && !params[:unpublished]) %>
					<% if !t.published_status %>
						<div class="index-row index-row-title"><%= link_to t.title, t %></div>
						<div class="index-row">Entwurf</div>
						<div class="index-row index-aktionen">
							<span><%= link_to "Bearbeiten", edit_track_path(t), class: 'user-edit-button'%></span>
							<span><%= link_to "Löschen", track_path(t), method: :delete, data: {confirm: "Willst Du wirklich diesen Track löschen?"}, class: 'user-edit-button', id: 'track-delete-button' %></span>
						</div>
					<% end %>
				<% end %>
			</div>
		<% end %>







		<% @tracks.each do |t| %>
			<div class="index-row-wrapper">

				<% if (!params[:published] && !params[:unpublished]) || (params[:published] == params[:unpublished]) %>
					<div class="index-row index-row-title"><%= link_to t.title, t %></div>
					<% if t.published_status %>
						<div class="index-row">Online</div>
					<% else %>
						<div class="index-row">Entwurf</div>
					<% end %>
					<div class="index-row index-aktionen">
						<span><%= link_to "Bearbeiten", edit_track_path(t), class: 'user-edit-button'%></span>
						<span><%= link_to "Löschen", track_path(t), method: :delete, data: {confirm: "Willst Du wirklich diesen Track löschen?"}, class: 'user-edit-button', id: 'track-delete-button' %></span>
					</div>
				<% elsif (params[:published] == '1') && (params[:unpublished] == '0') %>
					<div class="index-row index-row-title"><%= link_to t.title, t %></div>
					<div class="index-row">Online</div>
					<div class="index-row index-aktionen">
						<span><%= link_to "Bearbeiten", edit_track_path(t), class: 'user-edit-button'%></span>
						<span><%= link_to "Löschen", track_path(t), method: :delete, data: {confirm: "Willst Du wirklich diesen Track löschen?"}, class: 'user-edit-button', id: 'track-delete-button' %></span>
					</div>
				<% elsif (params[:published] == '0') && (params[:unpublished] == '1') %>
					<div class="index-row index-row-title"><%= link_to t.title, t %></div>
					<div class="index-row">Entwurf</div>
					<div class="index-row index-aktionen">
						<span><%= link_to "Bearbeiten", edit_track_path(t), class: 'user-edit-button'%></span>
						<span><%= link_to "Löschen", track_path(t), method: :delete, data: {confirm: "Willst Du wirklich diesen Track löschen?"}, class: 'user-edit-button', id: 'track-delete-button' %></span>
					</div>
				<% end %>
			</div>
		<% end %>

app/views/tracks/music.html.erb
<% provide(:title, 'Musik') %>

<div class="single-page" id="music-page">
	
	<% if params[:category_id].blank? %>
		<h2>Alle Tracks (<%= @tracks.size %>)</h2>
	<% else %>
		<% if @category.parent %>
			<h2>Kategorie <%= @category.parent.title %> - <%= @category.title %> (<%= @tracks.size %>)</h2>
		<% else %>
			<h2>Kategorie <%= @category.title %> (<%= @tracks.size %>) </h2>
		<% end %>
	<% end %>

	<div id="category-filter">
		<%= form_with(url: music_url, method: :get, local: true) do |f| %>


  	<%= f.select(:category_id, nested_dropdown(Category.all.arrange), prompt: "Kategorie wählen",) %>

		<%= f.submit "Filtern", class:'user-edit-button' %>
		<%= f.submit "Zurücksetzen", class:'user-edit-button' %>

		<% end %>
	</div>

	<div class="all-tracks-table">
		<%= render @tracks %>		
	</div>
</div>

app/views/tracks/new.html.erb
<% provide(:title, "Neuer Track")%>
<% provide(:button_text, "Neuen Track erstellen") %>

<div class="single-page", id="new-track-page">
	<h2>Neuen Track erstellen</h2>
	<%= render 'shared/track_form' %>
</div>

app/views/tracks/show.html.erb
<% provide :title, @track.title %>

<% if @track.published_status %>
<div class="single-page", id="show-track-page-published">
<% else %>
<div class="single-page", id="show-track-page-unpublished">
<% end %>
	
	<h2>
		<%= @track.title %>

		<!-- show edit and delete buttons to authors or admis only -->
		<% if current_user && ((@track.user_id == current_user.id) || super_admin_user?(current_user)) %>
			<%= link_to (fa_icon "pen"), edit_track_path(@track), class: "h2-fa-icon", alt: "Bearbeiten", title: "Bearbeiten" %>
			<%= link_to (fa_icon "trash-alt"), track_path(@track), method: :delete, data: { confirm: "Willst Du den Track wirklich löschen?" }, class: "h2-fa-icon", alt: "Löschen", title: "Löschen" %>	
		<% end %>
	</h2>

	<div id="track-show-div">
		<div id="track-show-image">
			<% if @track.image.attached? %>
				<%= image_tag @track.display_image, title: "#{@track.image.filename}", alt: "#{@track.image.filename}" %>
			<% end %>
		</div>

		<div id="track-show-attributes">
			<div id="track-attributes">
				<% if @track.description.length > 0 %>
					<p><%= @track.description %></p>
				<% end %>	
				<p>Lizenz: <%= link_to "CC BY", "https://creativecommons.org/licenses/?lang=en", target: '_blank' %></p>
				<p>
					<% if !@track.composer.blank? %>
						Komposition: <%= @track.composer %>
					<% end %>	
				</p>
				<p>Kategorie: <%= @cat_parent.title %> - <%= @cat.title %></p>
				<p class="track-show-audio-download">
					<span class="track-show-span"><%= audio_tag(url_for(@track.audio), controls: '') %></span>
					<span class="track-show-span" id="track-show-download"><%= link_to "Download", url_for(@track.audio), download: true, class: "user-edit-button" %></span>
				</p>
				<p>
					
				</p>
			</div>

			<div class="track-show-more">
				<h4>Weitere Tracks der Kategorie <%= link_to "#{@cat.parent.title} - #{@cat.title}", "/music?category_id=#{@cat.id}", class:'track-show-more-cat' %></h4>
				<% all_tracks = Track.where(category_id: @track.category_id).to_a %>
				<% all_tracks = all_tracks.select {|t| t!= @track } %>
				<% if all_tracks.size > 2 %>
					<% all_tracks = all_tracks.sample(2) %>
				<% end %>
				
				<div class="all-tracks-table" id="show-more-tracks">
						<%= render all_tracks %>		
					</div>
			</div>
		</div>
	</div>

</div>