config/routes.rb
Rails.application.routes.draw do
  root 'tracks#home'

  get 'videos/new'
  get 'videos/edit'
  get 'videos/index'
  get 'videos/show'
  get 'tracks/new'
  get 'tracks/create'
  get 'tracks/edit'
  get 'tracks/update'
  get 'tracks/show'
  get 'tracks/index'
  get 'tracks/destroy'
  get 'tracks/search', to: 'tracks#search'
  get 'password_resets/new'
  get 'password_resets/edit'
	# For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
    
  get '/signup', to: 'users#new'
  get '/in-kuerze', to:  'static_pages#in_kuerze' #test 
  get '/ueber-mich', to: 'static_pages#ueber_mich'
  get '/impressum', to: 'static_pages#impressum'
  get '/datenschutz', to: 'static_pages#datenschutz'
  get '/kontakt', to: 'static_pages#kontakt'
  get '/all_tracks', to: 'tracks#all_tracks'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  

  resources :users
  resources :videos
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]

  get '/music', to: 'tracks#music'

  resources :tracks



end

app/models/user.rb
class User < ApplicationRecord
	has_many :tracks
	has_many :videos
	attr_accessor :remember_token, :activation_token, :reset_token

	before_save :downcase_email
	before_create :create_activation_digest

	validates :name, presence: true, length: { maximum: 50 }
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
	validates :email, presence: true, length: { maximum: 255 }, format: { with: VALID_EMAIL_REGEX }, uniqueness: true

	has_secure_password
	validates :password, presence: true, length: { minimum: 8 }, allow_nil: true

	# Remembers a user in the database for use in persistent sessions.
	def remember
		self.remember_token = User.new_token
		update_attribute(:remember_digest, User.digest(self.remember_token))
		remember_digest
	end

	# Returns a session token to prevent session hijacking.
	# We reuse the remember digest for convenience.
	def session_token
		remember_digest || remember
	end

	# Returns true if the user is authenticated - if the remember token corresponds to the remember digest
	def authenticated?(attribute, token)
		digest = send("#{attribute}_digest")
		return false if digest.nil?
		BCrypt::Password.new(digest).is_password?(token)
	end

		# Forgets a user
	def forget
		update_attribute(:remember_digest, nil)
	end

	# Returns the hash digest of the given string
	def User.digest(string)
		cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
	end

	# Returns a random token
	def User.new_token
		SecureRandom.urlsafe_base64
	end

	# Activates an account
	def activate
		update_columns(activated: true, activated_at: Time.zone.now)
	end

	# Sends activation email
	def send_activation_email
		UserMailer.account_activation(self).deliver_now
	end

	# Creates and assigns the reset token and digest
	def create_reset_digest
		self.reset_token = User.new_token
		update_columns(reset_digest: User.digest(reset_token), reset_sent_at: Time.zone.now)
	end

	# Sends password reset email
	def send_password_reset_email
		UserMailer.password_reset(self).deliver_now
	end

	# Returns true if password reset has expired.
	def password_reset_expired?
		self.reset_sent_at < 2.hours.ago
	end

	private

		# Converts email to all lower-case
		def downcase_email
			email.downcase!
		end

		# Creates and assigns the activation token and digest
		def create_activation_digest
			self.activation_token = User.new_token
			self.activation_digest = User.digest(activation_token)
		end
	
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :logged_in_user, only: [:edit, :update, :show, :index, :destroy]
	before_action :correct_user, only: [:show, :edit, :update]
  before_action :admin_user?, only: [:destroy]

  def new
  	@user = User.new
  end

  # Creates a new user
  def create
  	@user = User.new(user_params)
  	if @user.save
  		@user.send_activation_email 
  		flash[:info] = "Wir haben Dir eine E-Mail zur Aktivierung Deines Accounts geschickt."
  		redirect_to root_url
      #reset_session
      #log_in @user
  		#flash[:success] = "Welcome to Soladis-Music!"
  		#redirect_to @user
  	else
  		render 'new'
  	end
  end

  # Shows a user
  def show
    @user = User.find(params[:id])
    @tracks = @user.tracks.paginate(page: params[:page])
    redirect_to root_url and return unless @user.activated?
  end

  # Edits a user
  def edit
  	@user = User.find_by(id: params[:id])
  end

  # Updates a user
  def update
    if @user.update(user_params)
      flash[:success] = "Dein Profil wurde erfolgreich aktualisiert."
      redirect_to @user
    else
      render 'edit'
    end  	
  end

  # Shows all users
  def index
  	@users = User.where(activated: true).paginate(page: params[:page])
  end

  # Destroys a user
  def destroy
    user = User.find(params[:id])
    if user.id != 1
      if user.tracks.size != 0
        user.tracks.each do |track|
          track.user_id = 1
          track.save
        end
      end
      user.destroy
      flash[:success] = "User wurde gelöscht"
      redirect_back(fallback_location: root_url)
    else
      flash[:danger] = "User ist Superadmin. Superadmin darf nicht gelöscht werden."
      redirect_to user_url
    end 
  	
  end

  private

  	def user_params
  		params.require(:user).permit(:name, :email, :password, :password_confirmation, :admin)
  	end

  	# Before filter

  	# Confirms the correct user
  	def correct_user
  		@user = User.find(params[:id])
      if current_user == @user || admin_user?
        return true
      else
        flash[:danger] = "Du hast keine Berechtigung für diese Seite. Weiterleitung zur Homepage"
        redirect_to root_url
      end
      #return false unless (current_user == @user || admin_user?)
  	end

  	# Confirms that the user is admin
  	def admin_user?
  		is_admin = false
  		if (current_user.admin? || current_user.superadmin?)
  			is_admin = true
  		else
  			is_admin = false
  		end
  		return is_admin
  	end
end

app/helpers/users_helper.rb
module UsersHelper

end

app/views/users/_user.html.erb
<li>
	<span id="user-name-index"><%= link_to user.name, user %></span> 
	<% if current_user.superadmin? || current_user.admin? || current_user?(user) %>
		<%= link_to "User bearbeiten", edit_user_url(user), class: "user-edit-button" %>
	<% end %>
	<% if (current_user.admin? || current_user.superadmin?) && !current_user?(user) %>
		<span>
			<%= link_to " Account löschen", user, method: :delete, data: { confirm: "Willst Du den User Account wirklich löschen?" }, class: "user-edit-button" %>
		</span>
	<% end %>
	
</li>

app/views/users/edit.html.erb
<% provide(:title, 'Profil aktualisieren') %>
<% provide(:button_text, 'Speichern') %>

<div class="single-page" id="update-profile-page">
	<h2>Profil aktualisieren</h2>
	<%= render 'shared/soladis-form' %>

</div>

app/views/users/index.html.erb
<% provide(:title, 'Alle User' )%>

<div class="single-page", id="index-page">
	<h2>Alle User</h2>

	<div id="show-all-users">
		<ul id="all-users-list">
			<%= render @users %>
		</ul>
	</div>
	
	<%= will_paginate %>
</div>

app/views/users/new.html.erb
<% provide(:title, 'Registrieren') %>
<% provide(:button_text, 'Registrieren') %>

<div class="single-page" id="signup">
	<h2>Registrieren</h2>
	
	<%= render 'shared/soladis-form' %>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name )%>

<div class = "single-page">
	<h2>
		<%= @user.name%>
	</h2>
	<p>
		<%= @user.email %>
	</p>

	<div id="my-dashboard-flexbox">
		
		<div id="my-roles-and-actions">
			<div id="my-roles">
				<h3>Meine Rollen</h3>
				<p>
					<% if !@user.admin? && !@user.superadmin? %>
						Keine Rollen<br>
					<% else %>	
						<% if @user.admin? %>
							Admin<br>
						<% end %>
						<% if @user.superadmin? %>
							Superadmin<br>
						<% end %>
					<% end %>	
				</p>
			</div>

			<div id="my-actions">
				<h3>Meine Aktionen</h3>
				<p>
					<%= link_to "Profil aktualisieren", edit_user_path(@user), class: 'user-edit-button' %>
					<%= link_to "Neue Musik erstellen", new_track_path, class: 'user-edit-button' %>
					<%= link_to "Neues Video erstellen", new_video_path, class: 'user-edit-button' %>
				</p>
			</div>
		</div>

		<div id="my-tracks">
			<h3>Meine Tracks</h3>
			<div>
				<p>Anzahl der Tracks: <%= @tracks.count %> </p>
			</div>
			<div class="index-table" id="index-table-users-show">
				<div class="index-heading">Titel</div>
				<div class="index-heading">Status</div>
				<!-- <div class="index-heading">Erstellt von</div> -->
				<div class="index-heading index-aktionen" id="index-heading-aktionen">Aktionen</div>

				<%= render @tracks %>
				<%= will_paginate @tracks %>
			</div>
		</div>
	</div>
	
</div>