config/routes.rb
Rails.application.routes.draw do
  root 'tracks#home'

  get 'videos/new'
  get 'videos/edit'
  get 'videos/index'
  get 'videos/show'
  get 'tracks/new'
  get 'tracks/create'
  get 'tracks/edit'
  get 'tracks/update'
  get 'tracks/show'
  get 'tracks/index'
  get 'tracks/destroy'
  get 'tracks/search', to: 'tracks#search'
  get 'password_resets/new'
  get 'password_resets/edit'
	# For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
    
  get '/signup', to: 'users#new'
  get '/in-kuerze', to:  'static_pages#in_kuerze' #test 
  get '/ueber-mich', to: 'static_pages#ueber_mich'
  get '/impressum', to: 'static_pages#impressum'
  get '/datenschutz', to: 'static_pages#datenschutz'
  get '/kontakt', to: 'static_pages#kontakt'
  get '/all_tracks', to: 'tracks#all_tracks'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  

  resources :users
  resources :videos
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]

  get '/music', to: 'tracks#music'

  resources :tracks



end

app/models/video.rb
class Video < ApplicationRecord
	belongs_to :user
	default_scope -> {order(created_at: :desc)}
	VALID_VIDEO_REGEX = /https:\/\/www.youtube.com\/embed\/\S+/
	validates :url, presence: true, format: { with: VALID_VIDEO_REGEX }, uniqueness: true
	validates :user_id, presence: true
	
	has_many :track_videos
	has_many :tracks, through: :track_videos

end

app/controllers/videos_controller.rb
 class VideosController < ApplicationController
	before_action :get_user, only: [:new, :create, :edit, :update, :destroy]
	before_action :about_video, only: [:show, :edit, :update, :destroy]

  def new
  	@video = @user.videos.build
  end

  # Creates new video
  def create
  	track_titles = params[:video][:used_tracks].gsub(", ", ",").split(',')
  	
  	@video = @user.videos.build(video_params)
  	@video.url["watch?v="] = "embed/" if @video.url.include?("watch?v=")
  	if @video.save
  		flash.now[:success] = "Neues Video hinzugefügt"
  		track_titles.each do |tt|
  			@video.track_videos.create(track_id: Track.find_by(title: tt).id)
  		end
  		redirect_to videos_path
  	else
  		flash.now[:danger] = "Das Hinzufügen von Video ist fehlgeschlagen"
  		render 'new'
  	end
  end

  def show
  end

  def edit
  end

  # Updates an existing video
  def update
  	existing_used_tracks = @video.used_tracks.split(', ')
  	new_used_tracks = params[:video][:used_tracks].split(', ')
  	track_videos_to_delete = existing_used_tracks - new_used_tracks
  	track_videos_to_create = new_used_tracks - existing_used_tracks
  	if @video.update(video_params)
  		flash[:success] = "Die Änderungen wurden gespeichert."
  		if track_videos_to_delete != [] # Track connections to be deleted
  			track_videos_to_delete.each do |t|
  				t = Track.find_by(title: t)
  				@video.track_videos.find_by(track_id: t.id).destroy
  			end
  		end

  		if track_videos_to_create != [] # Track connections to be created
  			track_videos_to_create.each do |t|
  				t = Track.find_by(title: t)
  				@video.track_videos.create(track_id: t.id)
  			end
  		end
  		redirect_to videos_path
  	else
  		flash[:danger] = "Das Video konnte nicht gespeichert werden."
  		redirect_to videos_path
  	end
  end

  # Shows all videos
  def index
  	@videos = Video.all
  	if @videos.size == 0
  		flash[:danger] = "Es existieren noch keine Videos"
  		redirect_to new_video_path
  	end
  end

  # Destroys a video
  def destroy
	  TrackVideo.where(video_id: @video.id).each { |tv| tv.destroy }
	  if @video.destroy
			flash[:success] = "Video wurde gelöscht."
		else
			flash[:danger] = "Das Löschen von Video schlug fehl."
		end  		

  	redirect_to videos_path

  end

  private

  	def video_params
  		params.require(:video).permit(:url, :used_tracks)
  	end

  	def get_user
  		if current_user == nil
  			store_location
  			flash[:info] = "Bitte logge Dich zuerst ein!"
  			redirect_to login_path
  		else
  			@user = current_user
  		end
  	end

    # Information about a video
  	def about_video
  		@video = Video.find_by(id: params[:id])
  		if !@video
  			flash[:danger] = "Das Video existiert nicht."
  			redirect_to videos_path
  		else # Video existiert
  			if request.path == edit_video_path(@video) || params[:action] == 'destroy'
					if !(@user.id == @video.user_id || super_admin_user?(@user))
  	  			flash[:danger] = "Du hast keine Berechtigung für diese Aktion."
  					redirect_to videos_path
  				end
  			end
  		end

  	end
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/videos/_video.html.erb
<div class="single-video">
	<span id="video-edit-icons">
		<!-- show edit and delete buttons to authors or admins only -->
		<% if current_user && (current_user.id == video.user_id || super_admin_user?(current_user)) %>
			<%= link_to (fa_icon "pen"), edit_video_path(video), class: "h2-fa-icon", alt: "Bearbeiten", title: "Bearbeiten" %>
			<%= link_to (fa_icon "trash-alt"), video_path(video), method: :delete, data: { confirm: "Willst Du das Video wirklich löschen?" }, class: "h2-fa-icon", alt: "Löschen", title: "Löschen" %>
		<% end %>
	</span><br>
	<iframe width="100%" height="345" src="<%= video.url %>"></iframe><br>
	<span>
		<span>
			Verwendete Tracks: 
			<% video.tracks.each_with_index do |t,ind| %>
				<%= link_to t.title, track_path(t) %><% if t != video.tracks.last %>,<% end %>
			<% end %>
		</span>
	</span>
</div>

app/views/videos/edit.html.erb
<% provide(:title, 'Video bearbeiten') %>
<% provide(:button_text, 'Speichern') %>

<div class="single-page", id="edit-video-page">
	<h2>Video bearbeiten</h2>
	<%= render 'shared/video_form' %>
</div>

app/views/videos/index.html.erb
<% provide(:title, "Video")%>

<div class="single-page", id="index-video-page">
	<h2>Videos mit Tracks von Soladis-Music</h2>
	<div class="video-wrapper">
		<%= render @videos %>
	</div>	
</div>

app/views/videos/new.html.erb
<% provide(:title, 'Neues Video') %>
<% provide(:button_text, 'Neues Video hinzufügen') %>

<div class="single-page", id="new-video-page">
	<h2>Neues Video</h2>
	<%= render 'shared/video_form' %>
</div>

app/views/videos/show.html.erb
<% provide(:title, "Video")%>

<div class="single-page">
	<iframe width="420" height="345" src="<%= @video.url %>"></iframe>
	<p>
		Verwendete Tracks: 
		<% @video.tracks.each do |t| %>
			<%= link_to t.title, track_path(t) %>
		<% end %>
	</p>
	<p>
		<%= link_to "Löschen", video_path(@video), method: :delete, data: {confirm: "Willst Du das Video wirlich löschen?"} %>
	</p>
</div>