config/routes.rb
Rails.application.routes.draw do
  root 'tracks#home'

  get 'videos/new'
  get 'videos/edit'
  get 'videos/index'
  get 'videos/show'
  get 'tracks/new'
  get 'tracks/create'
  get 'tracks/edit'
  get 'tracks/update'
  get 'tracks/show'
  get 'tracks/index'
  get 'tracks/destroy'
  get 'tracks/search', to: 'tracks#search'
  get 'password_resets/new'
  get 'password_resets/edit'
	# For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
    
  get '/signup', to: 'users#new'
  get '/in-kuerze', to:  'static_pages#in_kuerze' #test 
  get '/ueber-mich', to: 'static_pages#ueber_mich'
  get '/impressum', to: 'static_pages#impressum'
  get '/datenschutz', to: 'static_pages#datenschutz'
  get '/kontakt', to: 'static_pages#kontakt'
  get '/all_tracks', to: 'tracks#all_tracks'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  

  resources :users
  resources :videos
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]

  get '/music', to: 'tracks#music'

  resources :tracks



end

app/views/layouts/_footer.html.erb
<footer>

	<div>
		<span>soladis-music &copy <%= current_year %> Alle Rechte vorbehalten</span>
	</div>

	<nav id="footer-menu">
		<ul class="nav-ul" id="footer-menu-list">
			<li>
				<%= link_to('Datenschutzerklärung', datenschutz_path)%>
			</li>
			<li>
				<%= link_to('Impressum', impressum_path)%>
			</li>
		</ul>
	</nav>

</footer>

app/views/layouts/_header.html.erb
<header class="header-footer" id="header">

	<div id="title">
		<div id="soladis-title">
			<span><%= link_to "Soladis-Music", "https://soladis-music.net", class:'title-link' %></span>
		</div>
		<div id=soladis-subtitle>
			<%= link_to "Gemafreie Musik", "https://soladis-music.net", class:'title-link', id:'subtitle-link' %>
		</div>	
	</div>

	<div class="mobile-menu-bars" onclick="mobileMenuFunc()"><%= fa_icon "bars" %></div>

	<nav class="header-menu" id="header-menu-id">
		<ul class="nav-ul" id="header-menu-list">
			<li>
				<%= active_link_to('Home', 'https://soladis-music.net', active: :exclusive) %>
			</li>
			<li>
				<%= active_link_to('Musik', music_path, active: :exclusive) %>
			</li>
			<li>
				<%= active_link_to('Videos', videos_path, active: :exclusive) %>
			</li>
			<li>
				<%= active_link_to('In Kürze', in_kuerze_path, active: :exclusive) %>
			</li>
			<li>
				<%= active_link_to('Über mich', ueber_mich_path, active: :exclusive) %>
			</li>

			<!--<li>
				<%= link_to('Kontakt', kontakt_path) %>
			</li> -->
			<% if logged_in? %>
				<li id="meins-list-item">
					<%= link_to '#' do %>
						Meins <i class="fas fa-caret-down"></i>
					<% end %>
					<ul id="user-menu-list">
						<li class="user-menu-item">
							<%= link_to('Mein Profil', current_user) %>
						</li>
						<li class="user-menu-item">
							<%= link_to('Alle User', users_path)%>
						</li>
						<li class="user-menu-item">
							<%= link_to('Alle Tracks', tracks_path)%>
						</li>
						<li class="user-menu-item">
							<%= link_to('Neue Musik', new_track_path)%>
						</li>
						<li class="user-menu-item">
							<%= link_to('Neues Video', new_video_path)%>
						</li>
						<li id="divider-item"><hr></li>
						<li class="user-menu-item", id="logout-item">
							<%= link_to('Ausloggen', logout_path, method: :delete)%>
						</li>
					</ul>	
				</li>
					
			<% end %>
		</ul>
	</nav>
</header>
<script>
	function mobileMenuFunc() {
   var element = document.getElementById("header-menu-id");
   element.classList.toggle("mobile-menu-vis");
}
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width,initial-scale=1.0">
    <%= favicon_link_tag asset_path('favicon.ico') %>
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=El+Messiri:wght@400;500;600;700&display=swap" rel="stylesheet">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag '//ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/themes/le-frog/jquery-ui.min.css' %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!--Google Fonts -->
    <link href="https://fonts.googleapis.com/css2?family=Alegreya+Sans:ital,wght@0,100;0,300;0,400;0,500;1,100;1,300;1,400;1,500&family=Noto+Serif&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Fira+Sans&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Alegreya&family=Cormorant+Garamond:wght@300;400;500&family=Gentium+Basic&family=Lato:wght@300;400&family=Montserrat&family=Vollkorn&display=swap" rel="stylesheet"> 
    <link href="https://fonts.googleapis.com/css2?family=Lora:ital,wght@1,500;1,600;1,700&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Lora:wght@400;500&family=Nunito&family=PT+Sans&family=Roboto&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Philosopher:ital,wght@0,400;0,700;1,400;1,700&display=swap" rel="stylesheet"> 
    <link href="https://fonts.googleapis.com/css2?family=Barlow:wght@500;600;700;800;900&family=Cabin:wght@500;600;700&family=Encode+Sans+Condensed:wght@500;600;700;800;900&family=Encode+Sans+Semi+Condensed:wght@500;600;700;800;900&family=Encode+Sans:wght@500;600;700&family=Fira+Sans:wght@500;600;700;800;900&family=Lato:wght@700;900&family=Merriweather+Sans:wght@500;600;700;800&family=Noto+Sans+JP:wght@500;700;900&family=Noto+Sans+SC:wght@500;700;900&family=Poppins:wght@600;700;800;900&family=Rubik:wght@500;600;700;800;900&family=Source+Sans+Pro:wght@600;700;900&display=swap" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/cookieconsent@3/build/cookieconsent.min.css" />

  </head>

  <body>
    <%= render 'layouts/header' %>
    <div>
    	<% flash.each do |message_type, message| %>
    		<div class="alert alert-<%= message_type %>"><%= message %></div>
    	<% end %>
    </div>
    <%= yield %>
    <%= render 'layouts/footer' %>
    
    <script src="https://cdn.jsdelivr.net/npm/cookieconsent@3/build/cookieconsent.min.js" data-cfasync="false"></script>
    <script>
      window.cookieconsent.initialise({
        "palette": {
          "popup": {
            "background": "#efefef",
            "text": "#363230"
          },
          "button": {
            "background": "#00999b",
            "text": "#ffffff",
            "font-family": "SangBleuSunrise-Regular"
          }
        },
        "theme": "classic",
        "position": "bottom-right",
        "content": {
          "message": "Diese Website verwendet Cookies, um sie möglichst benutzerfreundlich zu gestalten. Wenn Sie auf der Seite weitersurfen, stimmen Sie der Verwendung dieser Cookies zu.",
          "dismiss": "OK",
          "link": "Weitere Informationen",
          "href": "datenschutz"
        }
      });
    </script>
  </body>
  
</html>